spring:
  application:
    name: document-service
  config:
    import: "optional:configserver:http://localhost:8888"
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

